In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3], dtype = 'int64')

In [0]:
print(a)

[1 2 3]


In [0]:
a

array([1, 2, 3])

In [0]:
type(a)

numpy.ndarray

In [0]:
a.ndim

1

In [0]:
b = np.array([[1,2,3],[1,2,3]])

In [0]:
print(b)

[[1 2 3]
 [1 2 3]]


In [0]:
b.ndim

2

In [0]:
type(b[0])

numpy.ndarray

In [0]:
type(a[0])

numpy.int8

In [0]:
a.itemsize

8

In [0]:
b.itemsize

8

In [0]:
b.nbytes

48

In [0]:
b.size

6

In [0]:
a.size

3

In [0]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [0]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [0]:
a[1,5]

13

In [0]:
a[:, : ]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [0]:
a[1, 3 : -1 : 3]

array([11])

In [0]:
a[1,5] = 31

In [0]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 31, 14]])

In [0]:
a[0, :] = a[1,2]

In [0]:
a

array([[10, 10, 10, 10, 10, 10, 10],
       [ 8,  9, 10, 11, 12, 31, 14]])

In [0]:
c = np.array([[[1,2],[4,4],[3,4],[5,5]],[[1,2],[4,4],[3,4],[5,5]],[[1,2],[4,4],[3,4],[5,5]]])

In [0]:
print

<function print>

In [0]:
c.ndim

3

In [0]:
c.shape

(3, 3, 2)

In [0]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [0]:
c = np.array([[[1, 2],[3,4]],[[2, 3],[7,8]]])

In [0]:
print(c)

[[[1 2]
  [3 4]]

 [[2 3]
  [7 8]]]


In [0]:
c.shape

(2, 2, 2)

In [0]:
c[0][1] = [9,9]

In [0]:
c

array([[[1, 2],
        [9, 9]],

       [[2, 3],
        [7, 8]]])

In [0]:
c[1][1] = [8,8]

In [0]:
c

array([[[1, 2],
        [9, 9]],

       [[2, 3],
        [8, 8]]])

In [0]:
c.shape

(2, 2, 2)

In [0]:
#initializing different types of arrays

In [0]:
zero = np.zeros((3,3,3), dtype = 'int16')

In [0]:
zero.shape

(3, 3, 3)

In [0]:
zero

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [0]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
type(zero[0][0][1])

numpy.int16

In [0]:
np.full((3,3), 100, dtype='int32')

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]], dtype=int32)

In [0]:
np.full_like(zero, 8)

array([[[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]], dtype=int16)

In [0]:
np.random.rand(4,2)

array([[0.86573916, 0.92134752],
       [0.6181545 , 0.29993575],
       [0.6466166 , 0.89700649],
       [0.92487156, 0.95155529]])

In [0]:
np.random.randint(1,6, size =(1,1))

array([[5]])

In [0]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3 , axis = 0)

In [0]:
r1.shape

(3, 3)

In [0]:
##manipulating arrays , copyuing and stuff like that

In [0]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [0]:
output[1:-1,1:-1] = z

In [0]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])