In [0]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


In [0]:
iris = load_iris()
X = iris.data[:,(2,3)]

print(X)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [0]:
y = (iris.target==0).astype(np.int8)


In [0]:
p = Perceptron(tol=0.001)

p.fit(X, y)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
for val in X:
  pred = p.predict([val])


In [0]:
import sys
import warnings
warnings.simplefilter('ignore')

print(__doc__)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

tuned_parameters = [{'tol': [0.01,0.001,0.0001]}]

scores = ['precision', 'recall']


for score in scores:

  print("#Tuning")
  print()
  cv_list = [5,10,15,20,25]
  for cv1 in cv_list:

    clf = GridSearchCV(Perceptron(), tuned_parameters, cv= cv1, scoring='%s_macro' % score)

    clf.fit(X_train, y_train)

    print("Best parameters set found on set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on dev set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']

    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
      print("%0.3f (+/-%0.03f) for %r" % (mean, std*2, params))


    print()
    print("Classification report:")



    y_true, y_pred = y_test, clf.predict(X_test)

    print(classification_report(y_true, y_pred))
    print()

Automatically created module for IPython interactive environment
#Tuning

Best parameters set found on set:

{'tol': 0.01}

Grid scores on dev set:

1.000 (+/-0.000) for {'tol': 0.01}
1.000 (+/-0.000) for {'tol': 0.001}
1.000 (+/-0.000) for {'tol': 0.0001}

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00        21

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75


Best parameters set found on set:

{'tol': 0.01}

Grid scores on dev set:

1.000 (+/-0.000) for {'tol': 0.01}
1.000 (+/-0.000) for {'tol': 0.001}
1.000 (+/-0.000) for {'tol': 0.0001}

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00        21

    accuracy        

In [0]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(activation = "identity",solver='lbfgs', alpha = 1e-5, 
                    hidden_layer_sizes = (5,2,4,12))
clf.fit(X,y)

MLPClassifier(activation='identity', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 2, 4, 12), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
print("weights between IP layers and 1st hidden layer")
print(clf.coefs_[0])

weights between IP layers and 1st hidden layer
[[ 1.02436188 -0.67598342 -0.51031967 -0.75783918 -0.59308647]
 [ 0.23755349  1.00193418  1.01858044  0.36246472 -0.64457503]]


In [0]:
print("Weights between 1st hidden layer and second hidden layer")
print(clf.coefs_[1])

Weights between 1st hidden layer and second hidden layer
[[ 4.33669352e-01  9.33994486e-01]
 [-5.57622864e-01  1.88483178e+00]
 [ 4.24331605e-04 -9.15869050e-01]
 [ 9.82079776e-01 -1.45892427e+00]
 [ 4.92238337e-01 -2.60935892e-01]]


In [0]:
for i in range(len(clf.coefs_)):
  number_neurons_in_layer = clf.coefs_[i].shape[1]
  for j in range(number_neurons_in_layer):
    weights = clf.coefs_[i][:,j]
    print(i, j, weights, end=", ")
    print()

  print()


0 0 [1.02436188 0.23755349], 
0 1 [-0.67598342  1.00193418], 
0 2 [-0.51031967  1.01858044], 
0 3 [-0.75783918  0.36246472], 
0 4 [-0.59308647 -0.64457503], 

1 0 [ 0.03940324  0.37857496  0.27690177 -0.72453501 -0.1160194 ], 
1 1 [-0.71289707 -0.71652786 -0.5874469   1.10270373  0.93496514], 

2 0 [ 0.35507418 -0.63064788], 
2 1 [-0.45542853 -0.44149395], 
2 2 [ 0.48950151 -0.58775843], 
2 3 [-0.72884244  0.62010313], 

3 0 [ 0.49897502 -0.06619717  0.37483611 -0.47579489], 
3 1 [-0.12462634 -0.32538838  0.05835175 -0.42291279], 
3 2 [-0.53248967 -0.00092455 -0.30658678  0.62375057], 
3 3 [ 0.22673788  0.6200271   0.4215815  -0.59031781], 
3 4 [ 0.97170498 -0.2019838  -0.09039529 -0.2777248 ], 
3 5 [-0.19201404 -0.29335473 -0.31899886  0.58417149], 
3 6 [-0.47289068 -0.41636795 -0.15571846  0.35281696], 
3 7 [-0.20961926 -0.55294214 -0.44741315  0.35224215], 
3 8 [-0.32184549 -0.1802043   0.11032736  0.09742057], 
3 9 [ 0.0190543  -0.19122595 -0.64324411 -0.05747365], 
3 10 [-0.364246

In [0]:
import sys
import warnings
warnings.simplefilter('ignore')

print(__doc__)


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

tuned_parameters = [{'hidden_layer_sizes' : [(100, ), (200, ), (400, ), (500, )],
                     'activation' : ['identity', 'logistic', 'tanh', 'relu'],
                     'solver' : ['lbfgs'],
                     'alpha' : [0.001, 0.0001, 0.00001],
                     'learning_rate' : ['constant', 'invscaling', 'adaptive']}]

scores = ['precision', 'recall']


for score in scores:

  print("#Tuning")
  print()
  cv_list = [5,10,15,20,25]
  for cv1 in cv_list:

    clf = GridSearchCV(MLPClassifier(), tuned_parameters, cv= cv1, scoring='%s_macro' % score)

    clf.fit(X_train, y_train)

    print("Best parameters set found on set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on dev set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']

    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
      print("%0.3f (+/-%0.03f) for %r" % (mean, std*2, params))


    print()
    print("Classification report:")



    y_true, y_pred = y_test, clf.predict(X_test)

    print(classification_report(y_true, y_pred))
    print()

Automatically created module for IPython interactive environment
#Tuning

Best parameters set found on set:

{'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (100,), 'learning_rate': 'constant', 'solver': 'lbfgs'}

Grid scores on dev set:

1.000 (+/-0.000) for {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (100,), 'learning_rate': 'constant', 'solver': 'lbfgs'}
1.000 (+/-0.000) for {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (100,), 'learning_rate': 'invscaling', 'solver': 'lbfgs'}
1.000 (+/-0.000) for {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (100,), 'learning_rate': 'adaptive', 'solver': 'lbfgs'}
1.000 (+/-0.000) for {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (200,), 'learning_rate': 'constant', 'solver': 'lbfgs'}
1.000 (+/-0.000) for {'activation': 'identity', 'alpha': 0.001, 'hidden_layer_sizes': (200,), 'learning_rate': 'invscaling', 'solver': 'lbfgs'}
1.000 (+/-0.000) for {'activat